# Generated by Django 5.2.9 on 2025-12-05 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logs/')),
                ('video', models.FileField(blank=True, null=True, upload_to='logs_video/')),
                ('area', models.CharField(choices=[('social', 'Social'), ('trabalho', 'Trabalho'), ('fe', 'Fé'), ('familia', 'Família'), ('saude', 'Corpo & Mente')], default='social', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('val_count', models.PositiveIntegerField(default=0)),
                ('echo_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
